/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountInfo: typeof import('./components/AccountInfo.vue')['default']
    AppButton: typeof import('./components/AppButton.vue')['default']
    AppNavbar: typeof import('./components/AppNavbar.vue')['default']
    NFTCollectionModal: typeof import('./components/nft/NFTCollectionModal.vue')['default']
    NFTCreateModal: typeof import('./components/nft/NFTCreateModal.vue')['default']
    NFTDetailModal: typeof import('./components/nft/NFTDetailModal.vue')['default']
    NFTGrid: typeof import('./components/nft/NFTGrid.vue')['default']
    NoSidechainAccountModal: typeof import('./components/NoSidechainAccountModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserProfilePage: typeof import('./components/nft/UserProfilePage.vue')['default']
  }
}
